### ISSUE TITLE
Server crash when placing auto sieve

### ISSUE THREAD

**Issue by P1-Kashwak** [MikeLydeamore/Ex-Astris#60]
I am using v1.16-30 and i am getting this error when the server crashes.

java.lang.NoSuchMethodError: exnihilo.registries.SieveRegistry.registered(Lnet/minecraft/block/Block;I)Z
	at ExAstris.Block.TileEntity.TileEntitySieveAutomatic.func_94041_b(TileEntitySieveAutomatic.java:476)
	at cofh.lib.util.helpers.InventoryHelper.addToEmptyInventorySlot(InventoryHelper.java:219)
	at cofh.lib.util.helpers.InventoryHelper.insertItemStackIntoInventory(InventoryHelper.java:151)
	at cofh.lib.util.helpers.InventoryHelper.addToInsertion(InventoryHelper.java:363)
	at cofh.thermalexpansion.util.Utils.addToInventory(Utils.java:53)
	at cofh.thermalexpansion.block.TileInventory.transferItem(TileInventory.java:73)
	at cofh.thermalexpansion.block.machine.TilePulverizer.transferProducts(TilePulverizer.java:172)
	at cofh.thermalexpansion.block.machine.TileMachineBase.func_145845_h(TileMachineBase.java:106)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by MikeLydeamore** [comment]
Update Ex Nihilo.
