### ISSUE TITLE
Crash with Java 6

### ISSUE THREAD

**Issue by codycoolwaffle** [MikeLydeamore/Ex-Astris#81]
I have tried everything i could. I have been trying to build a modpack, and this weird thing keeps happening when i have ex astris! I have tried removing all other mods besides ex nihilo & ex astris, but still a crash! someone please help...

CRASH REPORT:

B#301]  [15:54:03] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
[B#301]  // Who set us up the TNT?
[B#301]  
[B#301]  Time: 5/14/15 3:54 PM
[B#301]  Description: There was a severe problem during mod loading that has caused the game to fail
[B#301]  
[B#301]  cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: ExAstris.ExAstris
[B#301]     at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
[B#301]     at cpw.mods.fml.common.Loader.loadMods(Loader.java:522)
[B#301]     at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:206)
[B#301]     at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
[B#301]     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
[B#301]     at net.minecraft.client.main.Main.main(SourceFile:148)
[B#301]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#301]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[B#301]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[B#301]     at java.lang.reflect.Method.invoke(Method.java:597)
[B#301]     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#301]     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[B#301]  Caused by: java.lang.ClassNotFoundException: ExAstris.ExAstris
[B#301]     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[B#301]     at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[B#301]     at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[B#301]     at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:58)
[B#301]     at java.lang.Class.forName0(Native Method)
[B#301]     at java.lang.Class.forName(Class.java:249)
[B#301]     at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
[B#301]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#301]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[B#301]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[B#301]     at java.lang.reflect.Method.invoke(Method.java:597)
[B#301]     at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[B#301]     at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[B#301]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[B#301]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[B#301]     at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[B#301]     at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[B#301]     at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[B#301]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#301]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[B#301]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[B#301]     at java.lang.reflect.Method.invoke(Method.java:597)
[B#301]     at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[B#301]     at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[B#301]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[B#301]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[B#301]     at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[B#301]     at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[B#301]     at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
[B#301]     ... 10 more
[B#301]  Caused by: java.lang.UnsupportedClassVersionError: ExAstris/ExAstris : Unsupported major.minor version 51.0
[B#301]     at java.lang.ClassLoader.defineClass1(Native Method)
[B#301]     at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[B#301]     at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[B#301]     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[B#301]     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[B#301]     ... 38 more
[B#301]  
[B#301]  
[B#301]  A detailed walkthrough of the error, its code path and all known details is as follows:
[B#301]  ---------------------------------------------------------------------------------------
[B#301]  
[B#301]  -- System Details --
[B#301]  Details:
[B#301]     Minecraft Version: 1.7.10
[B#301]     Operating System: Mac OS X (x86_64) version 10.10.3
[B#301]     Java Version: 1.6.0_65, Apple Inc.
[B#301]     Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
[B#301]     Memory: 42180472 bytes (40 MB) / 140709888 bytes (134 MB) up to 4286251008 bytes (4087 MB)
[B#301]     JVM Flags: 2 total; -Xmx4096m -XX:MaxPermSize=256m
[B#301]     AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
[B#301]     IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
[B#301]     FML: MCP v9.05 FML v7.10.141.1403 Minecraft Forge 10.13.3.1403 5 mods loaded, 5 mods active
[B#301]     mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
[B#301]     FML{7.10.141.1403} [Forge Mod Loader](modpack.jar) Unloaded->Constructed
[B#301]     Forge{10.13.3.1403} [Minecraft Forge](modpack.jar) Unloaded->Constructed
[B#301]     exnihilo{1.37} [Ex Nihilo](Ex-Nihilo-1.37.jar) Unloaded->Constructed
[B#301]     exastris{MC1.7.10-1.16-35} [Ex Astris](Ex-Astris-MC1.7.10-1.16-35.jar) Unloaded->Errored
[B#301]     GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-1.32.20' Renderer: 'ATI Radeon HD 5670 OpenGL Engine'
[B#301]  [15:54:03] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# /Users/boysCPU/Library/Application Support/technic/modpacks/wafflez-in-da-sky/crash-reports/crash-2015-05-14_15.54.03-client.txt

**Comment by tterrag1098** [comment]
Appears ExAstris is not compatible with java 6, this is a bug and should be fixed. For now you can fix your issue by installing java 7.

**Comment by MikeLydeamore** [comment]
Java 7 compliance (at least at compiletime) is required for Tinkers Steelworks API. This is probably still my fault, but I'm bad at versioning.

**Comment by tterrag1098** [comment]
But...you have the TSteelworks API as compiled class files...
